### Import necessary Library 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Import Data From Sklearn. datasets

In [2]:
from sklearn.datasets import fetch_california_housing
california_housing = fetch_california_housing()

In [3]:
california_housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
california_housing.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [5]:
california_housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [6]:
california_housing.target_names

['MedHouseVal']

In [7]:
california_housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [8]:
print(california_housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

### Create data Frame 

In [9]:
df =pd.DataFrame(california_housing.data ,columns=california_housing.feature_names)
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

### Concat Target Var in dataFrame

In [10]:
df["target_MedHouseVal"] =california_housing.target

In [11]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target_MedHouseVal  
0    -122.23               4.526  
1    -122.22               3.585  
2    -122.24               3.521  
3    -122.25               3.413  
4    -122.25               3.422

In [12]:
df.shape

(20640, 9)

In [13]:
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'target_MedHouseVal'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   MedInc              20640 non-null  float64
 1   HouseAge            20640 non-null  float64
 2   AveRooms            20640 non-null  float64
 3   AveBedrms           20640 non-null  float64
 4   Population          20640 non-null  float64
 5   AveOccup            20640 non-null  float64
 6   Latitude            20640 non-null  float64
 7   Longitude           20640 non-null  float64
 8   target_MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


### Chcek Null Values

In [15]:
df.isnull().sum()

MedInc                0
HouseAge              0
AveRooms              0
AveBedrms             0
Population            0
AveOccup              0
Latitude              0
Longitude             0
target_MedHouseVal    0
dtype: int64

### Check duplicate

In [16]:
df.duplicated().sum()

0

### Devide X & Y  

In [17]:
X =df.iloc[:,:-1] ### Independant Var
y =df.iloc[:,-1]  ### Independant Var

In [18]:
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [19]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target_MedHouseVal, Length: 20640, dtype: float64

### Train Test Split

In [20]:
from sklearn.model_selection import train_test_split

X_train ,X_test ,y_train, y_test =train_test_split(X ,y,test_size=0.32 ,random_state=123)

In [21]:
X_train.shape, X_test.shape ,y_train.shape ,y_test.shape

((14035, 8), (6605, 8), (14035,), (6605,))

### Scaling If reqired

In [22]:
from sklearn.preprocessing import StandardScaler

Scaler =StandardScaler()
Scaler

StandardScaler()

In [23]:
X_train =Scaler.fit_transform(X_train)
X_test  =Scaler.transform(X_test)

In [24]:
X_train

array([[-0.37730699, -0.92135683,  0.25571267, ..., -0.06186025,
         1.73605963, -2.10976252],
       [-0.33309526, -1.55912575,  0.30277623, ..., -0.06836806,
        -0.05289756, -0.76338136],
       [-1.25219216,  1.31083438, -1.02019614, ..., -0.14516103,
        -0.87244601,  0.69769152],
       ...,
       [ 0.92965937, -1.87801021,  0.20317696, ...,  0.03494339,
         0.7947497 , -1.08751016],
       [ 0.00232229,  1.23111326, -0.26435441, ..., -0.11894871,
         1.00549073, -1.42659875],
       [-0.71573537, -0.68219349,  0.02407898, ...,  0.04124152,
         0.27023869,  0.2488978 ]])

In [25]:
X_test

array([[-4.16781535e-02,  9.12228805e-01, -1.79780016e-01, ...,
        -4.17117095e-02,  1.22091489e+00, -1.52633068e+00],
       [ 7.98116667e-02, -1.55912575e+00,  1.44189255e-01, ...,
        -1.02483306e-03,  2.14041080e-01,  2.63857593e-01],
       [ 1.14938071e-01, -1.31996240e+00, -2.61662841e-02, ...,
         1.64550240e-01, -1.30329434e+00,  1.29608314e+00],
       ...,
       [-7.93171924e-01,  3.52965448e-02, -5.36149408e-01, ...,
        -3.04342441e-02, -7.08536321e-01,  6.97691520e-01],
       [-2.94799553e-01,  1.15139215e+00, -4.83943192e-01, ...,
        -7.08420538e-02,  9.63342522e-01, -1.25206786e+00],
       [-6.25515972e-01,  1.15017659e-01,  6.61861376e-01, ...,
        -9.52049937e-02, -9.03626307e-02, -6.83595813e-01]])

### Create Model

In [26]:
from sklearn.linear_model import LinearRegression

model =LinearRegression()
model

LinearRegression()

In [27]:
model.fit(X_train ,y_train)

LinearRegression()

In [28]:
model.coef_,   len(model.coef_)

(array([ 0.82471296,  0.11477569, -0.26738722,  0.30765923, -0.00405269,
        -0.04217109, -0.90244888, -0.87244677]),
 8)

In [29]:
model.intercept_

2.073591201995011

### Prediction 

In [30]:
y_pred =model.predict(X_test)
y_pred

array([2.38446646, 1.43883234, 2.03909165, ..., 1.61389753, 2.21373628,
       2.36911678])

### Performance & Evaluation Metrics

In [31]:
from sklearn.metrics import mean_absolute_error ,mean_squared_error ,r2_score

meansquareError =mean_squared_error(y_test ,y_pred)
meanAbsoluteError =mean_absolute_error(y_test ,y_pred)
r2_score =r2_score(y_test ,y_pred)

In [32]:
meansquareError

0.5186680103992781

In [33]:
meanAbsoluteError

0.5304892875523115

In [34]:
r2_score

0.6117603523874269

In [35]:
#### Adjuested R2 Score
(1 -r2_score)*(len(y_test)-1) /(len(y_test)- X_test.shape[1] -1)

0.38871052650597826

In [36]:
RMSE = np.sqrt(meansquareError)
RMSE

0.7201860942834692

### Pickle model 

In [38]:
import pickle
pickle.dump(model,open("regressor.pkl","wb"))

In [39]:
model =pickle.load(open("regressor.pkl","rb"))

In [40]:
model.predict(X_test)

array([2.38446646, 1.43883234, 2.03909165, ..., 1.61389753, 2.21373628,
       2.36911678])