### Import Necessary Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'plan

In [3]:
df =sns.load_dataset("diamonds")
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df.shape

(53940, 10)

In [5]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   carat    53940 non-null  float64 
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64 
 5   table    53940 non-null  float64 
 6   price    53940 non-null  int64   
 7   x        53940 non-null  float64 
 8   y        53940 non-null  float64 
 9   z        53940 non-null  float64 
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB


### Check duplicate Value

In [7]:
df.duplicated().sum()

146

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

### Check Nan Values

In [10]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [11]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [12]:
cat_col =[i for i in df.columns if df[i].dtypes == "category"]
cat_col

['cut', 'color', 'clarity']

### Check Unique Values

In [13]:
def UniqueVal(col):
    for i in col :
        print(f"Unique Value of colums ==>{i} ===>{df[i].unique()}")
        print("==================================================================================")

print(UniqueVal(cat_col))

Unique Value of colums ==>cut ===>['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']
Unique Value of colums ==>color ===>['E', 'I', 'J', 'H', 'F', 'G', 'D']
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']
Unique Value of colums ==>clarity ===>['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']
None


### Convert the columns into numerical

In [14]:
from sklearn.preprocessing import LabelEncoder
label =LabelEncoder()
df.cut =label.fit_transform(df.cut)
df.cut.value_counts()

2    21488
3    13748
4    12069
1     4891
0     1598
Name: cut, dtype: int64

In [15]:
df.color =label.fit_transform(df.color)
df.color.value_counts()

3    11262
1     9776
2     9520
4     8272
0     6755
5     5407
6     2802
Name: color, dtype: int64

In [16]:
df.clarity =label.fit_transform(df.clarity)
df.clarity.value_counts()

2    13032
5    12229
3     9150
4     8156
7     5056
6     3647
1     1784
0      740
Name: clarity, dtype: int64

In [17]:
df.head()

carat  cut  color  clarity  depth  table  price     x     y     z
0   0.23    2      1        3   61.5   55.0    326  3.95  3.98  2.43
1   0.21    3      1        2   59.8   61.0    326  3.89  3.84  2.31
2   0.23    1      1        4   56.9   65.0    327  4.05  4.07  2.31
3   0.29    3      5        5   62.4   58.0    334  4.20  4.23  2.63
4   0.31    1      6        3   63.3   58.0    335  4.34  4.35  2.75

In [18]:
df.dtypes

carat      float64
cut          int32
color        int32
clarity      int32
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [19]:
df.to_csv("diamondPriceclean")

### Devide X & Y Variable

In [20]:
X= df.drop("price",axis=1)
y= df["price"]

In [21]:
X

carat  cut  color  clarity  depth  table     x     y     z
0       0.23    2      1        3   61.5   55.0  3.95  3.98  2.43
1       0.21    3      1        2   59.8   61.0  3.89  3.84  2.31
2       0.23    1      1        4   56.9   65.0  4.05  4.07  2.31
3       0.29    3      5        5   62.4   58.0  4.20  4.23  2.63
4       0.31    1      6        3   63.3   58.0  4.34  4.35  2.75
...      ...  ...    ...      ...    ...    ...   ...   ...   ...
53935   0.72    2      0        2   60.8   57.0  5.75  5.76  3.50
53936   0.72    1      0        2   63.1   55.0  5.69  5.75  3.61
53937   0.70    4      0        2   62.8   60.0  5.66  5.68  3.56
53938   0.86    3      4        3   61.0   58.0  6.15  6.12  3.74
53939   0.75    2      0        3   62.2   55.0  5.83  5.87  3.64

[53794 rows x 9 columns]

In [22]:
y

0         326
1         326
2         327
3         334
4         335
         ... 
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53794, dtype: int64

### Train test Split

In [23]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.28,random_state=1)
X_train.shape ,X_test.shape ,y_train.shape ,y_test.shape

((38731, 9), (15063, 9), (38731,), (15063,))

### Scaling If required

In [24]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
X_train =scaler.fit_transform(X_train)
X_test  =scaler.transform(X_test)

In [25]:
X_train

array([[-0.56485023, -0.54040842, -1.53440834, ..., -0.47312738,
        -0.44240254, -0.44862057],
       [-0.41786433, -0.54040842, -0.3566719 , ..., -0.21548328,
        -0.200785  , -0.28003583],
       [-0.94281399,  1.40662029, -1.53440834, ..., -1.05948981,
        -1.05092079, -1.08081335],
       ...,
       [ 0.42205514,  0.43310593,  1.99880097, ...,  0.56633329,
         0.47932364,  0.60503405],
       [ 0.8000189 ,  0.43310593,  0.23219631, ...,  0.96612586,
         0.92676353,  0.88600862],
       [-0.90081802, -0.54040842,  0.82106453, ..., -0.9795313 ,
        -0.96143281, -0.92627733]])

In [26]:
X_test

array([[-1.04780393,  1.40662029, -0.94554012, ..., -1.29936535,
        -1.26569193, -1.23534936],
       [ 0.44305313, -0.54040842, -0.3566719 , ...,  0.58410185,
         0.6225044 ,  0.66122896],
       [-0.94281399, -0.54040842, -1.53440834, ..., -1.07725837,
        -1.06881838, -1.0105697 ],
       ...,
       [ 0.46405111,  1.40662029, -0.3566719 , ...,  0.66406036,
         0.55986282,  0.63313151],
       [-1.04780393, -0.54040842,  0.82106453, ..., -1.2371754 ,
        -1.26569193, -1.2072519 ],
       [ 0.4850491 , -0.54040842,  0.23219631, ...,  0.59298613,
         0.67619719,  0.68932642]])

### Create ML model 

In [27]:
from sklearn.linear_model import LinearRegression
Lr_model =LinearRegression()
Lr_model.fit(X_train ,y_train)

LinearRegression()

In [28]:
Lr_model.coef_

array([ 5238.31431824,    56.22398567,  -456.80329896,   484.44906341,
        -209.35901905,  -193.85816609, -3350.5991539 ,  2093.40958548,
         -27.8493111 ])

In [29]:
Lr_model.intercept_

3953.7399240918116

In [33]:
### Prediction
y_pred =Lr_model.predict(X_test)

In [34]:
y_pred

array([1448.50060348, 5978.45847522, 1547.53293656, ..., 4506.88328769,
        390.37259508, 5182.76573253])

In [35]:
from sklearn.metrics import mean_squared_error ,mean_absolute_error,r2_score
mse =mean_squared_error(y_test ,y_pred)
mse

2573818.801496235

In [37]:
mae =mean_absolute_error(y_test,y_pred)
mae

860.580791247999

In [38]:
r2_score(y_test,y_pred)

0.830041714957277

### Pickle model result

In [40]:
import pickle
pickle.dump(Lr_model ,open("Diamond_regressor.pkl","wb"))

In [41]:
model =pickle.load(open("Diamond_regressor.pkl","rb"))

In [43]:
model.predict(X_train)

array([2886.78941254, 2873.76030232, 1299.44754227, ..., 3561.8321917 ,
       6511.24661187, 1085.81228188])